LANGUAGE_CODE_MAP = {
    "hindi": "hi",
    "english": "en",
    "marathi": "mr",
    "punjabi": "pa",
    "bengali": "bn",
    "urdu": "ur",
    "tamil": "ta",
    "kannada": "kn",
    "telugu": "te",
    "gujarati": "gu",
    "malayalam": "ml",
    "odia": "or",
    "assamese": "as",
    "sanskrit": "sa",
    "sindhi": "sd",
    "dogri": "doi",
    "bhojpuri": "bh",
    "rajasthani": "raj",
    "haryanvi": "hi",
    "kashmiri": "ks",
    "bodo": "brx",
    "manipuri": "mni",
    "santali": "sat",
    "nepali": "ne",
    "konkani": "kok",
}
